id: P004383
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7900
  title: ཕར་ཕྱིན་སྤྱི་དོན།
  author: ''
  volumes:
    33dc5f34a1594278bbe9fc4224d4bb55:
      image_group_id: I1KG10539
      title: ''
      volume_number: 1
      total_pages: 766
      base_file: v001.txt
