id: P004383
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:16:57.917510
source_metadata:
  id: bdr:W2CZ7900
  title: ཕར་ཕྱིན་སྤྱི་དོན།
  author: ''
  volumes:
    33dc5f34a1594278bbe9fc4224d4bb55:
      image_group_id: I1KG10539
      title: ''
      volume_number: 1
      total_pages: 766
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
