id: IC9CF4F4C
legacy_id: P004383
ocr_import_info:
  bdrc_scan_id: W2CZ7900
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T12:15:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:26:04.795168+00:00'
last_modified: 2022-09-02 23:27:36.056688
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7900
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7900
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕར་ཕྱིན་སྤྱི་དོན།
  author: ཁྲི ༢༢་དགེ་འདུན་བསྟན་པ་དར་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.5439346494825347
  ocr_word_median_confidence_index: 0.5299999713897705
quality: null
bases:
  I1KG10539:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10539
      total_pages: 766
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10539.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5439346494825347
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
