id: IC9CF4F4C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:20:32+00:00'
last_modified: '2022-06-07T22:28:17.760128+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7900
  title: ཕར་ཕྱིན་སྤྱི་དོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3579':
      image_group_id: I1KG10539
      title: ''
      total_pages: 766
      order: 1
      base_file: 3579.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
